Fix for translation not working in graphql
scandipwa/cms-graphql pull request #17
Opened 2022-02-17 07:49 UTC by raivisdejus

This fixes the following Magento issue https://github.com/magento/magento2/issues/31351

Some additional info https://stackoverflow.com/questions/61770306/while-working-with-the-magento-2-graphql-it-seems-that-the-string-translation-do

2022-03-24 17:48 UTC, aleksandrsm commented on src/Plugin/InitGraphQlTranslations.php
> +    protected $areaList;
if this is to be merged into latest PWA, please use php 7.4 features - class property types
e.g. `protected AreaList $areaList;`

2022-03-24 17:49 UTC, aleksandrsm commented on src/Plugin/InitGraphQlTranslations.php
> +    protected $appState;
same here

2022-03-24 17:50 UTC, aleksandrsm commented on src/Plugin/InitGraphQlTranslations.php
> +        if ($area) {
newlines before if statements recommended (unless they're the only part of the code block)

2022-03-24 17:55 UTC, aleksandrsm commented on src/Plugin/InitGraphQlTranslations.php
> +        if ($area) {
same here

2022-03-24 18:02 UTC, aleksandrsm requested changes
see minor comments

& thanks for porting this fix to core PWA

2022-03-24 18:05 UTC, aleksandrsm commented on src/Plugin/InitGraphQlTranslations.php
> + * ScandiPWA_CmsGraphQl
personally, I'd put it in PersistedQuery module rather than CmsGraphQl, because it already has plugins on the GrapQL controller

2022-04-04 12:24 UTC, raivisdejus commented
`processGraphqlRequest()` is triggered in `aroundPlugin` and is to process cached queries. It is executed before the plugin on graphql controller
https://github.com/scandipwa/persisted-query/blob/master/src/Plugin/PersistedQuery.php#L227

So we need also this plugin to make translations work for all cases

2022-04-04 12:33 UTC, aleksandrsm commented
Odd, as `processRequest` is triggered by `aroundDispatch`, which I thought would be executing after the `beforeDispatch`, which the new plugin adds on the base class. Not 100% sure on how the before-around interaction on plugins work, specially with multiple plugins involved.
I guess it doesn't work when the `beforeDispatch` is defined on the base class but not the `PersistedQuery` plugin.

Keep as is if it is necessary, and thanks for checking.

2022-06-09 17:34 UTC, merged